---
editor: source
---



::: {.callout-tip title="Lernziele"}
- Maxwellgleichungen
- Feldgrößen der Elektromagnetik
- Materialgleichungen, Ohmsches Gesetz
:::

# Grundgleichungen

Feldgrößen werden im Zeitbereich als Funktion des Ortes und der Zeit gemessen, z.B.

$$
\mathbf{e} = \mathbf{e}(\mathbf{r}, t).
$$


Bei Verfahren mit Wechselfeldern kann die explizite Zeitabhängigkeit durch eine Fouriertransformation abgekoppelt werden.

::: {.callout-note title="Bemerkungen zur Notation"}
Im Zeitbereich werden die Feldgrößen kleingeschrieben, z.B. $\mathbf{e}$, $\mathbf{h}$. 

Im Frequenzbereich schreiben wir die Feldgrößen mit Großbuchstaben, z.B. $\mathbf{B}$.

Der Zusammenhang wird durch die Fouriertransformation hergestellt:

$$
\begin{align}
f(t) & = \frac{1}{2 \pi} \int_{-\infty}^{\infty} F(\omega) e^{ +i \omega t }\, \mathrm d  \omega \\
F(\omega) & = \phantom{\frac{1}{2 \pi}} \int_{-\infty}^{\infty} f(t) e^{ -i \omega t }\, \mathrm d t
\end{align}
$$

Die Zeitabhängigkeit wird durch den Term $e^{ i \omega t }$ eingeführt, und wir schreiben
$$
\mathbf{E}(\omega) = \mathbf{E}_{0} e^{ i \omega t }.
$$
Der Term $e^{ i \omega t }$ tritt bei allen Feldgrößen als derselbe Faktor auf und wird daher der besseren Übersicht halber weggelassen.

Die physikalisch relevante Größe ist die Feldamplitude $\mathbf{E}_{0}$.
:::

## Maxwell-Gleichungen

### Zeitbereich
$$
\begin{align}
\curl \mathbf{h} & = \mathbf{j} + \frac{ \partial \mathbf{d} }{ \partial t } \qq{Ampere} \\
\curl \mathbf{e} & = -\frac{ \partial \mathbf{b} }{ \partial t } \qq{Faraday} \\
\div \mathbf{b} & = 0 \qq{Gauß} \\
\div \mathbf{d} & = \rho_{E}
\end{align}
$$

### Frequenzbereich
$$
\begin{align}
\curl \mathbf{H} & = \mathbf{J} + i \omega \mathbf{D} \qq{Ampere} \\
\curl \mathbf{E} & = -i \omega \mathbf{B} \qq{Faraday} \\
\div \mathbf{B} & = 0 \qq{Gauß} \\
\div \mathbf{D} & = \rho_{E}
\end{align}
$$

## Materialgleichungen

$$
\begin{align}
\mathbf{b} & = \mu \mathbf{h} \\
\mathbf{d} & = \varepsilon \mathbf{e}
\end{align}
$$

bzw.
$$
\begin{align}
\mathbf{B} & = \mu \mathbf{H} \\
\mathbf{E} & = \varepsilon \mathbf{E}
\end{align}
$$


## Ohmsches Gesetz
$$
\mathbf{j} = \sigma \mathbf{e} \quad\text{  bzw.  }\quad \mathbf{J} = \sigma \mathbf{E}.
$$


